id: P006988
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD105917
  title: བོད་རིག་པའི་སྐོར་གྱི་རྩོམ་ཡིག་ཐོར་བུ།
  author: ''
  volumes:
    c27d3a72ee83428797d210b5abb3eef9:
      image_group_id: I1PD105919
      title: ''
      volume_number: 1
      total_pages: 186
ebook_metadata:
  title: བོད་རིག་པའི་སྐོར་གྱི་རྩོམ་ཡིག་ཐོར་བུ།
  author: ''
  sku: P006988
  cover: cover.jpg
  layers:
  - pagination
