id: IF9A0E944
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T13:01:12+00:00'
last_modified: '2022-06-08T09:52:28.504570+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD105917
  title: བོད་རིག་པའི་སྐོར་གྱི་རྩོམ་ཡིག་ཐོར་བུ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '8571':
      image_group_id: I1PD105919
      title: Volume 1 of bod rig pa'i skor gyi rtsom yig thor bu
      total_pages: 186
      order: 1
      base_file: 8571.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
